version: '3'
services:
  database:
    image: mysql
  web:
    build: ./web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web:/project
      - ./data:/data
    ports:
      - "8000:8000"
    depends_on:
      - database
  proxy:
    build: ./proxy
    command: mitmdump -s script.py
#    command: mitmweb --web-iface 0.0.0.0
    volumes:
      - ~/.mitmproxy:/home/mitmproxy/.mitmproxy
      - ./proxy:/project
      - ./data:/data
    ports:
      - "8080:8080"
      - "8081:8081"
